import { ReportDocument } from '@/types/report';
import { formatDate } from '@/utils/format';

type R = ReportDocument & { cellStyles?: Record<string, string> };
const totals = ['مجموع المدفوع لكل عميل', 'المتبقي لتغطية قيمة السند المطلوب', 'المتبقي من رأس المال'];

function latin(v: string | number): string {
  const e = '٠١٢٣٤٥٦٧٨٩', p = '۰۱۲۳۴۵۶۷۸۹';
  return String(v ?? '').replace(/[٠-٩]/g, d => String(e.indexOf(d))).replace(/[۰-۹]/g, d => String(p.indexOf(d))).replace(/٫/g, '.').replace(/٬/g, ',').replace(/[‏‎]/g, '').trim();
}
function x(v: string | number): string { return latin(v).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;'); }
function col(n: number): string { let s = ''; while (n) { const r = (n - 1) % 26; s = String.fromCharCode(65 + r) + s; n = Math.floor((n - 1) / 26); } return s; }
function utf8(s: string): number[] { const a: number[] = []; for (let i = 0; i < s.length; i++) { let c = s.charCodeAt(i); if (c >= 0xd800 && c <= 0xdbff) { const d = s.charCodeAt(++i); c = 0x10000 + ((c - 0xd800) << 10) + (d - 0xdc00); } if (c < 128) a.push(c); else if (c < 2048) a.push(192 | c >> 6, 128 | c & 63); else if (c < 65536) a.push(224 | c >> 12, 128 | c >> 6 & 63, 128 | c & 63); else a.push(240 | c >> 18, 128 | c >> 12 & 63, 128 | c >> 6 & 63, 128 | c & 63); } return a; }
function b64(a: number[]): string { const c = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'; let s = ''; for (let i = 0; i < a.length; i += 3) { const x = a[i], y = i + 1 < a.length ? a[i + 1] : 0, z = i + 2 < a.length ? a[i + 2] : 0, t = x << 16 | y << 8 | z; s += c[t >> 18 & 63] + c[t >> 12 & 63] + (i + 1 < a.length ? c[t >> 6 & 63] : '=') + (i + 2 < a.length ? c[t & 63] : '='); } return s; }
const ct = Array.from({ length: 256 }, (_, i) => { let c = i; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ c >>> 1 : c >>> 1; return c >>> 0; });
function crc(a: number[]): number { let c = 0xffffffff; for (const b of a) c = ct[(c ^ b) & 255] ^ c >>> 8; return (c ^ 0xffffffff) >>> 0; }
function p16(o: number[], n: number) { o.push(n & 255, n >>> 8 & 255); }
function p32(o: number[], n: number) { o.push(n & 255, n >>> 8 & 255, n >>> 16 & 255, n >>> 24 & 255); }
function zip(files: Array<{ n: string; d: string }>): string { const o: number[] = [], cd: number[] = []; for (const f of files) { const n = utf8(f.n), d = utf8(f.d), c = crc(d), off = o.length; p32(o, 0x04034b50); p16(o, 20); p16(o, 2048); p16(o, 0); p16(o, 0); p16(o, 0); p32(o, c); p32(o, d.length); p32(o, d.length); p16(o, n.length); p16(o, 0); o.push(...n, ...d); p32(cd, 0x02014b50); p16(cd, 20); p16(cd, 20); p16(cd, 2048); p16(cd, 0); p16(cd, 0); p16(cd, 0); p32(cd, c); p32(cd, d.length); p32(cd, d.length); p16(cd, n.length); p16(cd, 0); p16(cd, 0); p16(cd, 0); p16(cd, 0); p32(cd, 0); p32(cd, off); cd.push(...n); } const off = o.length; o.push(...cd); p32(o, 0x06054b50); p16(o, 0); p16(o, 0); p16(o, files.length); p16(o, files.length); p32(o, cd.length); p32(o, off); p16(o, 0); return b64(o); }
function style(r: R, row: number, cell: number, label: string, header: number): number { if (row === 0) return 1; if (label === 'الملخص') return 2; if (row === header) return 3; if (row > header) { const rr = row - header - 1, tone = cell > 0 ? r.cellStyles?.[`${rr}:${cell}`] : ''; if (tone === 'paid') return 6; if (tone === 'due') return 7; if (tone === 'late') return 8; if (cell === 0) return 4; if (totals.includes(label)) return 5; } return 0; }

export function buildXlsxBase64(report: ReportDocument): string {
  const r = report as R;
  const rows: Array<Array<string | number>> = [[r.title], [r.subtitle], [`تاريخ الإنشاء: ${formatDate(r.generatedAt)}`], [], ['الملخص'], ...r.summary.map(i => [i.label, i.value]), [], r.headers, ...r.rows];
  const cols = Math.max(...rows.map(row => row.length), 1), header = 7 + r.summary.length;
  const sheetRows = rows.map((row, ri) => `<row r="${ri + 1}">${Array.from({ length: cols }, (_, ci) => `<c r="${col(ci + 1)}${ri + 1}" t="inlineStr" s="${style(r, ri, ci, String(row[0] || ''), header)}"><is><t>${x(row[ci] ?? '')}</t></is></c>`).join('')}</row>`).join('');
  const sheet = `<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheetViews><sheetView rightToLeft="1" workbookViewId="0"><pane ySplit="${header + 1}" topLeftCell="A${header + 2}" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="1" width="32" customWidth="1"/><col min="2" max="${cols}" width="18" customWidth="1"/></cols><sheetData>${sheetRows}</sheetData><mergeCells count="1"><mergeCell ref="A1:${col(cols)}1"/></mergeCells></worksheet>`;
  const styles = `<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="4"><font><sz val="11"/><name val="Arial"/></font><font><b/><sz val="11"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Arial"/></font><font><b/><color rgb="FF991B1B"/><sz val="11"/><name val="Arial"/></font></fonts><fills count="8"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FFEDE9FE"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFDBEAFE"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFE2E8F0"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFEF3C7"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFDCFCE7"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFEE2E2"/></patternFill></fill></fills><borders count="2"><border/><border><left style="thin"/><right style="thin"/><top style="thin"/><bottom style="thin"/></border></borders><cellXfs count="9"><xf fontId="0" fillId="0" borderId="1" applyBorder="1"><alignment horizontal="right" vertical="center" wrapText="1"/></xf><xf fontId="1" fillId="2" borderId="1" applyFill="1" applyFont="1" applyBorder="1"><alignment horizontal="right" wrapText="1"/></xf><xf fontId="1" fillId="3" borderId="1" applyFill="1" applyFont="1" applyBorder="1"><alignment horizontal="right" wrapText="1"/></xf><xf fontId="2" fillId="0" borderId="1" applyFont="1" applyBorder="1"><alignment horizontal="right" wrapText="1"/></xf><xf fontId="1" fillId="4" borderId="1" applyFill="1" applyFont="1" applyBorder="1"><alignment horizontal="right" wrapText="1"/></xf><xf fontId="1" fillId="5" borderId="1" applyFill="1" applyFont="1" applyBorder="1"><alignment horizontal="right" wrapText="1"/></xf><xf fontId="1" fillId="6" borderId="1" applyFill="1" applyFont="1" applyBorder="1"><alignment horizontal="right" wrapText="1"/></xf><xf fontId="1" fillId="3" borderId="1" applyFill="1" applyFont="1" applyBorder="1"><alignment horizontal="right" wrapText="1"/></xf><xf fontId="3" fillId="7" borderId="1" applyFill="1" applyFont="1" applyBorder="1"><alignment horizontal="right" wrapText="1"/></xf></cellXfs></styleSheet>`;
  return zip([{ n: '[Content_Types].xml', d: '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>' }, { n: '_rels/.rels', d: '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>' }, { n: 'xl/workbook.xml', d: '<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><workbookViews><workbookView rightToLeft="1"/></workbookViews><sheets><sheet name="التقرير" sheetId="1" r:id="rId1"/></sheets></workbook>' }, { n: 'xl/_rels/workbook.xml.rels', d: '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>' }, { n: 'xl/styles.xml', d: styles }, { n: 'xl/worksheets/sheet1.xml', d: sheet }]);
}
